---
- hosts: all
  become: yes

  tasks:

   - name: create docker image using war file
     command: docker build -t simple-devops-image:latest
     args:
       chdir: /opt/docker

   - name: create tag to image 
     command: docker tag simple-devops-image alagarramasamy/simple-devops-image

   - name: push image on to dockerhub
     command: docker push alagarramasamy/simple-devops-image

   - name: remove docker image from ansible
     command: docket rmi tomcat simple-devops-image:latest alagarramasamy/simple-devops-image
     ignore_errors: yes